// users.js
export const users = [
  {
    name: "John Doe",
    username: "johndoe",
    contact: "john.doe@example.com",
    role: "Manager",
    created_at: "2025-08-01",
    actions: "",
  },
  {
    name: "Jane Smith",
    username: "janesmith",
    contact: "jane.smith@example.com",
    role: "Seller",
    created_at: "2025-08-05",
    actions: "",
  },
  {
    name: "Michael Brown",
    username: "michaelb",
    contact: "michael.brown@example.com",
    role: "Supervisor",
    created_at: "2025-08-08",
    actions: "",
  },
  {
    name: "Emily Davis",
    username: "emilyd",
    contact: "emily.davis@example.com",
    role: "Designer",
    created_at: "2025-07-29",
    actions: "",
  },
  {
    name: "David Wilson",
    username: "davidw",
    contact: "david.wilson@example.com",
    role: "Sales Lead",
    created_at: "2025-08-02",
    actions: "",
  },
  {
    name: "Sophia Johnson",
    username: "sophiaj",
    contact: "sophia.johnson@example.com",
    role: "Brand Ambassador",
    created_at: "2025-07-25",
    actions: "",
  },
  {
    name: "Liam Martinez",
    username: "liamm",
    contact: "liam.martinez@example.com",
    role: "Engineer",
    created_at: "2025-08-07",
    actions: "",
  },
  {
    name: "Olivia Taylor",
    username: "oliviat",
    contact: "olivia.taylor@example.com",
    role: "Editor",
    created_at: "2025-07-31",
    actions: "",
  },
  {
    name: "Noah Anderson",
    username: "noaha",
    contact: "noah.anderson@example.com",
    role: "Musician",
    created_at: "2025-08-03",
    actions: "",
  },
  {
    name: "Ava Thomas",
    username: "avat",
    contact: "ava.thomas@example.com",
    role: "Travel Agent",
    created_at: "2025-07-28",
    actions: "",
  },
];
